export default [
  {
    OMSId: 1,
    ProductId: 1,
    Product: "BTC",
    ProductFullName: "Bitcoin",
    MasterDataUniqueProductSymbol: "",
    ProductType: "CryptoCurrency",
    DecimalPlaces: 8,
    TickSize: 1e-8,
    NoFees: false,
    IsDisabled: false,
    MarginEnabled: false,
  },
  {
    OMSId: 1,
    ProductId: 2,
    Product: "LTC",
    ProductFullName: "Litecoin",
    MasterDataUniqueProductSymbol: "",
    ProductType: "CryptoCurrency",
    DecimalPlaces: 8,
    TickSize: 1e-8,
    NoFees: false,
    IsDisabled: false,
    MarginEnabled: false,
  },
  {
    OMSId: 1,
    ProductId: 3,
    Product: "ETH",
    ProductFullName: "Ethereum",
    MasterDataUniqueProductSymbol: "",
    ProductType: "CryptoCurrency",
    DecimalPlaces: 8,
    TickSize: 1e-8,
    NoFees: false,
    IsDisabled: false,
    MarginEnabled: false,
  },
  {
    OMSId: 1,
    ProductId: 4,
    Product: "XRP",
    ProductFullName: "Ripple",
    MasterDataUniqueProductSymbol: "",
    ProductType: "CryptoCurrency",
    DecimalPlaces: 8,
    TickSize: 1e-8,
    NoFees: false,
    IsDisabled: false,
    MarginEnabled: false,
  },
  {
    OMSId: 1,
    ProductId: 5,
    Product: "BRL",
    ProductFullName: "Reais",
    MasterDataUniqueProductSymbol: "",
    ProductType: "NationalCurrency",
    DecimalPlaces: 2,
    TickSize: 0.01,
    NoFees: false,
    IsDisabled: false,
    MarginEnabled: false,
  },
  {
    OMSId: 1,
    ProductId: 6,
    Product: "BCH",
    ProductFullName: "Bitcoin Cash",
    MasterDataUniqueProductSymbol: "",
    ProductType: "CryptoCurrency",
    DecimalPlaces: 8,
    TickSize: 1e-8,
    NoFees: false,
    IsDisabled: false,
    MarginEnabled: false,
  },
  {
    OMSId: 1,
    ProductId: 7,
    Product: "USDT",
    ProductFullName: "Tether USD",
    MasterDataUniqueProductSymbol: "",
    ProductType: "CryptoCurrency",
    DecimalPlaces: 8,
    TickSize: 1e-8,
    NoFees: false,
    IsDisabled: false,
    MarginEnabled: false,
  },
  {
    OMSId: 1,
    ProductId: 8,
    Product: "LINK",
    ProductFullName: "Chainlink",
    MasterDataUniqueProductSymbol: "",
    ProductType: "CryptoCurrency",
    DecimalPlaces: 8,
    TickSize: 1e-8,
    NoFees: false,
    IsDisabled: false,
    MarginEnabled: false,
  },
  {
    OMSId: 1,
    ProductId: 9,
    Product: "DOGE",
    ProductFullName: "Dogecoin",
    MasterDataUniqueProductSymbol: "",
    ProductType: "CryptoCurrency",
    DecimalPlaces: 8,
    TickSize: 1e-8,
    NoFees: false,
    IsDisabled: false,
    MarginEnabled: false,
  },
  {
    OMSId: 1,
    ProductId: 10,
    Product: "ADA",
    ProductFullName: "Cardano",
    MasterDataUniqueProductSymbol: "",
    ProductType: "CryptoCurrency",
    DecimalPlaces: 8,
    TickSize: 1e-8,
    NoFees: false,
    IsDisabled: false,
    MarginEnabled: false,
  },
  {
    OMSId: 1,
    ProductId: 11,
    Product: "EOS",
    ProductFullName: "EOS.IO",
    MasterDataUniqueProductSymbol: "",
    ProductType: "CryptoCurrency",
    DecimalPlaces: 8,
    TickSize: 1e-8,
    NoFees: false,
    IsDisabled: false,
    MarginEnabled: false,
  },
  {
    OMSId: 1,
    ProductId: 12,
    Product: "XLM",
    ProductFullName: "Stellar",
    MasterDataUniqueProductSymbol: "",
    ProductType: "CryptoCurrency",
    DecimalPlaces: 8,
    TickSize: 1e-8,
    NoFees: false,
    IsDisabled: false,
    MarginEnabled: false,
  },
  {
    OMSId: 1,
    ProductId: 13,
    Product: "CHZ",
    ProductFullName: "Chiliz",
    MasterDataUniqueProductSymbol: "",
    ProductType: "CryptoCurrency",
    DecimalPlaces: 8,
    TickSize: 1e-8,
    NoFees: false,
    IsDisabled: false,
    MarginEnabled: false,
  },
  {
    OMSId: 1,
    ProductId: 14,
    Product: "SUSHI",
    ProductFullName: "SushiSwap",
    MasterDataUniqueProductSymbol: "",
    ProductType: "CryptoCurrency",
    DecimalPlaces: 2,
    TickSize: 0.01,
    NoFees: false,
    IsDisabled: false,
    MarginEnabled: false,
  },
  {
    OMSId: 1,
    ProductId: 15,
    Product: "USDC",
    ProductFullName: "USD Coin",
    MasterDataUniqueProductSymbol: "",
    ProductType: "CryptoCurrency",
    DecimalPlaces: 8,
    TickSize: 1e-8,
    NoFees: false,
    IsDisabled: false,
    MarginEnabled: false,
  },
  {
    OMSId: 1,
    ProductId: 16,
    Product: "AXS",
    ProductFullName: "Axie Infinity",
    MasterDataUniqueProductSymbol: "",
    ProductType: "CryptoCurrency",
    DecimalPlaces: 8,
    TickSize: 1e-8,
    NoFees: false,
    IsDisabled: false,
    MarginEnabled: false,
  },
  {
    OMSId: 1,
    ProductId: 17,
    Product: "BNB",
    ProductFullName: "Binance Coin",
    MasterDataUniqueProductSymbol: "",
    ProductType: "CryptoCurrency",
    DecimalPlaces: 8,
    TickSize: 1e-8,
    NoFees: false,
    IsDisabled: false,
    MarginEnabled: false,
  },
  {
    OMSId: 1,
    ProductId: 18,
    Product: "SLP",
    ProductFullName: "Smooth Love Potion",
    MasterDataUniqueProductSymbol: "",
    ProductType: "CryptoCurrency",
    DecimalPlaces: 0,
    TickSize: 1,
    NoFees: false,
    IsDisabled: false,
    MarginEnabled: false,
  },
  {
    OMSId: 1,
    ProductId: 19,
    Product: "UNI",
    ProductFullName: "Uniswap",
    MasterDataUniqueProductSymbol: "",
    ProductType: "CryptoCurrency",
    DecimalPlaces: 8,
    TickSize: 1e-8,
    NoFees: false,
    IsDisabled: false,
    MarginEnabled: false,
  },
  {
    OMSId: 1,
    ProductId: 20,
    Product: "CAKE",
    ProductFullName: "PancakeSwap",
    MasterDataUniqueProductSymbol: "",
    ProductType: "CryptoCurrency",
    DecimalPlaces: 8,
    TickSize: 1e-8,
    NoFees: false,
    IsDisabled: false,
    MarginEnabled: false,
  },
  {
    OMSId: 1,
    ProductId: 21,
    Product: "DOT",
    ProductFullName: "Polkadot",
    MasterDataUniqueProductSymbol: "",
    ProductType: "CryptoCurrency",
    DecimalPlaces: 8,
    TickSize: 1e-8,
    NoFees: false,
    IsDisabled: false,
    MarginEnabled: false,
  },
  {
    OMSId: 1,
    ProductId: 22,
    Product: "SHIB",
    ProductFullName: "SHIBA INU",
    MasterDataUniqueProductSymbol: "",
    ProductType: "CryptoCurrency",
    DecimalPlaces: 0,
    TickSize: 1,
    NoFees: false,
    IsDisabled: false,
    MarginEnabled: false,
  },
  {
    OMSId: 1,
    ProductId: 23,
    Product: "MATIC",
    ProductFullName: "Polygon",
    MasterDataUniqueProductSymbol: "",
    ProductType: "CryptoCurrency",
    DecimalPlaces: 8,
    TickSize: 1e-8,
    NoFees: false,
    IsDisabled: false,
    MarginEnabled: false,
  },
  {
    OMSId: 1,
    ProductId: 24,
    Product: "TRX",
    ProductFullName: "TRON",
    MasterDataUniqueProductSymbol: "",
    ProductType: "CryptoCurrency",
    DecimalPlaces: 8,
    TickSize: 1e-8,
    NoFees: false,
    IsDisabled: false,
    MarginEnabled: false,
  },
  {
    OMSId: 1,
    ProductId: 25,
    Product: "DAI",
    ProductFullName: "Dai",
    MasterDataUniqueProductSymbol: "",
    ProductType: "CryptoCurrency",
    DecimalPlaces: 8,
    TickSize: 1e-8,
    NoFees: false,
    IsDisabled: false,
    MarginEnabled: false,
  },
  {
    OMSId: 1,
    ProductId: 26,
    Product: "AAVE",
    ProductFullName: "Aave",
    MasterDataUniqueProductSymbol: "",
    ProductType: "CryptoCurrency",
    DecimalPlaces: 8,
    TickSize: 1e-8,
    NoFees: false,
    IsDisabled: false,
    MarginEnabled: false,
  },
  {
    OMSId: 1,
    ProductId: 27,
    Product: "MANA",
    ProductFullName: "Decentraland",
    MasterDataUniqueProductSymbol: "",
    ProductType: "CryptoCurrency",
    DecimalPlaces: 8,
    TickSize: 1e-8,
    NoFees: false,
    IsDisabled: false,
    MarginEnabled: false,
  },
  {
    OMSId: 1,
    ProductId: 28,
    Product: "SAND",
    ProductFullName: "The Sandbox",
    MasterDataUniqueProductSymbol: "",
    ProductType: "CryptoCurrency",
    DecimalPlaces: 8,
    TickSize: 1e-8,
    NoFees: false,
    IsDisabled: false,
    MarginEnabled: false,
  },
  {
    OMSId: 1,
    ProductId: 29,
    Product: "ENJ",
    ProductFullName: "Enjin Coin",
    MasterDataUniqueProductSymbol: "",
    ProductType: "CryptoCurrency",
    DecimalPlaces: 8,
    TickSize: 1e-8,
    NoFees: false,
    IsDisabled: false,
    MarginEnabled: false,
  },
  {
    OMSId: 1,
    ProductId: 30,
    Product: "ILV",
    ProductFullName: "Illuvium",
    MasterDataUniqueProductSymbol: "",
    ProductType: "CryptoCurrency",
    DecimalPlaces: 8,
    TickSize: 1e-8,
    NoFees: false,
    IsDisabled: false,
    MarginEnabled: false,
  },
  {
    OMSId: 1,
    ProductId: 31,
    Product: "ALICE",
    ProductFullName: "MyNeighborAlice",
    MasterDataUniqueProductSymbol: "",
    ProductType: "CryptoCurrency",
    DecimalPlaces: 8,
    TickSize: 1e-8,
    NoFees: false,
    IsDisabled: false,
    MarginEnabled: false,
  },
  {
    OMSId: 1,
    ProductId: 32,
    Product: "ATOM",
    ProductFullName: "Cosmos",
    MasterDataUniqueProductSymbol: null,
    ProductType: "CryptoCurrency",
    DecimalPlaces: 8,
    TickSize: 1e-8,
    NoFees: false,
    IsDisabled: false,
    MarginEnabled: false,
  },
  {
    OMSId: 1,
    ProductId: 33,
    Product: "EGLD",
    ProductFullName: "Elrond",
    MasterDataUniqueProductSymbol: null,
    ProductType: "CryptoCurrency",
    DecimalPlaces: 8,
    TickSize: 1e-8,
    NoFees: false,
    IsDisabled: false,
    MarginEnabled: false,
  },
  {
    OMSId: 1,
    ProductId: 34,
    Product: "FTM",
    ProductFullName: "Fantom",
    MasterDataUniqueProductSymbol: null,
    ProductType: "CryptoCurrency",
    DecimalPlaces: 8,
    TickSize: 1e-8,
    NoFees: false,
    IsDisabled: false,
    MarginEnabled: false,
  },
  {
    OMSId: 1,
    ProductId: 35,
    Product: "GRT",
    ProductFullName: "The Graph",
    MasterDataUniqueProductSymbol: null,
    ProductType: "CryptoCurrency",
    DecimalPlaces: 8,
    TickSize: 1e-8,
    NoFees: false,
    IsDisabled: false,
    MarginEnabled: false,
  },
];
